# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: fido-node
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 2000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 10
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 100
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakapi.dokutsu.xyz
          plugin_wakatime_user: fido_node
